### ISSUE TITLE
Not using keys with JSX Metal Components produces strange behavior

### ISSUE THREAD

**Issue by AngeloYoun** [metal/metal.js#107]
There seems to be an issue when not using keys for metal-jsx. This component is supposed to be adding more inputs but instead adds duplicate copies of itself when the 'Add Filter' button is clicked.

<img width="967" alt="screen shot 2016-05-09 at 11 16 32 am" src="https://cloud.githubusercontent.com/assets/11049786/15123223/b236f240-15d7-11e6-8497-6115df7f0729.png">

Manually setting keys to the components resolves this issue.

https://github.com/AngeloYoun/liferay-plugins-ee/blob/ZOE-177/portlets/watson-portlet/docroot/js/src/components/dynamic_select_input.js

**Comment by mairatma** [comment]
Thanks for reporting, will investigate.

**Comment by mairatma** [comment]
I figured out why this is happening, it's actually a bug in the app code, not in the infra (though it would be nice to make it easier to debug things like this, no idea right now but I'll think about it).

This is happening because you're [overriding the constructor](https://github.com/AngeloYoun/liferay-plugins-ee/blob/ZOE-177/portlets/watson-portlet/docroot/js/src/components/dynamic_select_input.js#L13), but you're calling `super` with only the first argument passed to it. Metal component constructors can receive 2 arguments, the second one specifying where the component is supposed to be rendered, or if it should skip rendering altogether. Sub components always skip rendering through the constructor, but since you're not passing the value it would receive it's rendering twice, and on the wrong position.

Also, from what I saw the reason why you're overriding the constructor is to bind the functions you'll be using inside `render`. That should actually be done in the `created`  lifecycle instead, since that happens before the first render, while at the end of the constructor the component may have already been rendered. Look at this [example](https://github.com/mairatma/metal-zoe/blob/master/src/js/components/incident-creation/IncidentCreationForm.js#L11).

By changing this for both `DynamicInputSelect` and `SelectInput` I managed to fix the problem, but you should make sure to do this for any other components, since I was just testing these ones.

As I said, I'll try to find of a way to try to make these kind of problems clearer.

**Comment by AngeloYoun** [comment]
Thanks Maira, that makes sense. Will use the created to bind functions.

**Comment by mairatma** [comment]
Sure, if all works as expected with these changes let me know so we can close this :)

**Comment by mairatma** [comment]
I'll close this since from what you told me this is working fine now :)

Just FYI, the other issue you mentioned with keys is being tracked by https://github.com/metal/metal-incremental-dom/issues/6.

**Comment by natecavanaugh** [comment]
@AngeloYoun FYI, a general good policy if you do need to overwrite the constructor (whether in Metal, or  React) is to do:

``` js
constructor(...args) {
    super(...args);
}
```

And even if you need some named ones, you can always use the spread operator to pass along any you're not aware of :)
