### ISSUE TITLE
Automatically make "this.config.children" accessible directly on "this.children".

### ISSUE THREAD

**Issue by ethib137** [metal/metal.js#118]
Can we make children available directly on the component instead of having to access them through the config or manually add "children" to Component.STATE = {}. 

This would be treating children in a similar way to elementClasses. 

It would be great if we could also apply the metal-state-validator for array when it is a JSX component. 

Do you see any negatives to this?

**Comment by mairatma** [comment]
It'd be fine to make `children` be a state property automatically for `JSXComponent`. I think we should avoid using `metal-state-validator` there though, since the idea is to have it be an optional library that people can use if they want a behavior more similar to react, but not to have it as a Metal.js default. Would that be ok?

**Comment by ethib137** [comment]
Yeah, that's fine... using the metal-state-validator isn't essential. Thanks.

**Comment by mairatma** [comment]
Done [here](https://github.com/metal/metal-jsx/issues/7). After updating the dependency you'll be able to use this already.
