### ISSUE TITLE
`onClick` event fires for both left and right click in firefox

### ISSUE THREAD

**Issue by bryceosterhaus** [metal/metal.js#152]
Create a jsx component like so

``` jsx
class MyComponent extends Component {
    render() {
        return (
            <div onClick={() => console.log("fire")}>MyComponent</div>
        );
    }
}
```

Render the component and use firefox. Click on the MyComponent text with a "right click". The console log will fire.

This does not happen in Chrome. I am currently running FF@46.0.1

I have not tested this in soy.

**Comment by mairatma** [comment]
You're right. I took a look and it seems like Firefox has some special behavior for right clicks. Like all other browsers, it doesn't trigger `onclick` for right clicks on regular elements, but it still [triggers it for the document](https://bugzilla.mozilla.org/show_bug.cgi?id=184051). Since we use delegate logic on the document, we end up triggering it for regular elements too.

I'll see what I can do to go around this Firefox problem so it doesn't affect us.
