### ISSUE TITLE
Add support for Portals

### ISSUE THREAD

**Issue by robframpton** [metal/metal.js#330]
See https://reactjs.org/docs/portals.html.

Portals allow components to render sub components to a different part of the DOM than where they are declared. This is to solve z-index and overflow hidden issues with components such as dropdowns, modals, and tooltips.

**Comment by eduardolundgren** [comment]
If I understood correctly "portal" ability means to take the element specified to be the component element then render the children nodes inside it.

The [third option](https://github.com/metal/metal.js/blob/master/packages/metal-component/src/Component.js#L513) of Metal component `render(Ctor, configOrElement, element)` specifies a different parent to render the component element.

The "portal" is different because of it uses the specified node as the component element instead of the parent of the component element.

Did I get it right?
If yes, the implementation prob. can be simplified.

**Comment by robframpton** [comment]
It's specifically for child components, rather than the root level component where you would be passing a parent element to render to. The parent element can't be used for a child component because it is not the element that is passed to Incremental DOM's `patch` function, it is only used when attaching the component to the DOM.

I put together a [demo](https://ui-metalportaldemo.wedeploy.io/) built from my branch to show how it might be used.

**Comment by eduardolundgren** [comment]
Got it. LGTM.
