### ISSUE TITLE
Solidify proper project name

### ISSUE THREAD

**Issue by blzaugg** [metal/metal.js#85]
Is it Metal, MetalJS, Metal JS, Metal.js?

"Metal", on it's own, will not Google well.

I assume it's Metal.js. We should refer to it consistently as Metal.js, not Metal.

Also, since this is early in it's life, should the project url (liferay/metal) in Github be updated to liferay/metal.js or liferay/metaljs?

**Comment by zenorocha** [comment]
Good point @blzaugg. For now, these are the names we registered:

## Domain
- [metaljs.com](http://metaljs.com/) will contain docs for the project

## Social
- [twitter.com/metaljs](http://twitter.com/metaljs)
- [npmjs.com/package/metaljs](http://npmjs.com/package/metaljs)
- [bower.io/search/?q=metaljs](http://bower.io/search/?q=metaljs)
- [stackoverflow.com/questions/tagged/metaljs](http://stackoverflow.com/questions/tagged/metaljs)

## GitHub
- [github.com/metaljs](https://github.com/metaljs) we're not planning to use this one, we just created to make sure nobody will get it
- [liferay/metal](https://github.com/liferay/metal) will contain the core foundation
- [liferay/metaljs.com](https://github.com/liferay/metaljs.com) will contain the website for this project
- [liferay/generator-metal](https://github.com/liferay/generator-metal) will contain the tool to scaffold a component (it needs to start with "generator" because that's how Yeoman generators are defined)

**Comment by zenorocha** [comment]
We're able to rename the GitHub repo to _liferay/metal.js_ or _liferay/metaljs_.

But we also need to keep in mind those who will create components using `metal` as a prefix to identify that it uses Metal.js, for example: [metal-position](https://github.com/eduardolundgren/metal-position).

**Comment by blzaugg** [comment]
I think `metal-position` is fine, as those people and searches for it should correlate to our project just fine.

**Comment by zenorocha** [comment]
I think we can rename this repo `metal.js`. Both https://github.com/eduardolundgren/tracking.js and https://github.com/angular/angular.js have been successful when using this `.js` suffix.

Thanks @blzaugg!

**Comment by blzaugg** [comment]
Related PR: https://github.com/liferay/metal.js/pull/86
